DEBUG: false
SERVER_NAME: 127.0.0.1:5000
BIND_HOST: 127.0.0.1:5000
CLOUDS_RESET: true
PLUGINS:
    provision_server: image
cmds:
    ping: &ping
        cmd: "ping %"

    ssh: &ssh
        cmd: "echo y | nc % 22"

    customerMonitoring: &customerMonitoring
        cmd: "curl '$MONITORING_URL/status.cgi?=%'"

    simpleWebCheck: &simpleWebCheck
        cmd: "curl http://%/$REQUEST_URI"

CLOUDS:
    source:
        environment: source-env
        endpoint:
            auth_url:    http://127.0.0.1:5000/v2.0
            username:    admin
            password:    nomoresecrete
            tenant_name: admin
        identity:
            connection:  mysql+mysqlconnector://root:root@127.0.0.1/keystone
        populate:
            num_servers: 3
            num_tenants: 3
        urls:
            horizon:        http://10.0.0.1/
        workloads:
            flavors:
              - &small
                name: pumphouse-flavor-0001-small
                ram: 1024
                vcpus: 1
                disk: 10
              - &medium
                name: pumphouse-flavor-0001-medium
                ram: 4096
                vcpus: 2
                disk: 40
              - &large
                name: pumphouse-flavor-0001-large
                ram: 8192
                vcpus: 4
                disk: 80
            images:
              - &image
                name: pumphouse-test-image-0001
                url: http://download.cirros-cloud.net/0.3.2/cirros-0.3.2-x86_64-disk.img
            volumes:
              - &volume
                display_name: pumphouse-test-volume-0001
                size: 1
            tenants:
              - name: pumphouse-test-0001
                description: "pumphouse test tenant 0001"
                username: pumphouse-test-user-0001
                volumes:
                  - &volume-1
                    display_name: pumphouse-volume-1
                    size: 1
                  - &volume-2
                    display_name: pumphouse-volume-2
                    size: 1
                  - &volume-3
                    display_name: pumphouse-volume-3
                    size: 1
                servers:
                  - name: pumphouse-test-instance-0001
                    flavor:
                      <<: *small
                    image:
                      <<: *image
                    volumes:
                      - <<: *volume-1
                      - <<: *volume-2
                    pre-actions: &health_checks
                        -
                            - <<: *ping
                              input:
                                  - public
                                  - private
                            - <<: *ssh
                              input:
                                  - public
                                  - private
                        - <<: *customerMonitoring
                          env:
                                MONITORING_URL: "http://monitoring.customer.int/cgi-bin"
                        - <<: *simpleWebCheck
                          env:
                                REQUEST_URI: "/index2.html"
                    post-actions:
                        <<: *health_checks
                  - name: pumphouse-test-instance-0002
                    flavor:
                      <<: *medium
                    image:
                      <<: *image
                    volumes:
                      - <<: *volume-3
                  - name: pumphouse-test-instance-0003
                    flavor:
                      <<: *large
                    image:
                      <<: *image
    destination:
        environment: source-env
        endpoint:
            auth_url: http://127.0.0.1:5000/v2.0
            username: admin
            password: secrete
            tenant_name: admin
        identity:
            connection: mysql+mysqlconnector://keystone:keystone@127.0.0.1/keystone
        urls:
            horizon:        http://horizon.endpoint.com/
            mos:            http://127.0.0.1:8000/
    fuel:
        endpoint:
            host: 172.18.167.155
            port: 8000
            username: admin
            password: admin
